echo "Regions available in ENSEMBL annotation (Homo_sapiens.GRCh38.100)
CDS
C_gene_segment
D_gene_segment
J_gene_segment
V_gene_segment
biological_region
chromosome
exon
five_prime_UTR
gene
lnc_RNA
mRNA
miRNA
ncRNA
ncRNA_gene
pseudogene
pseudogenic_transcript
rRNA
scRNA
scaffold
snRNA
snoRNA
tRNA
three_prime_UTR
unconfirmed_transcript
vaultRNA_primary_transcript

Regions available in EBI_GENCODE annotation (gencode.v34.chr_patch_hapl_scaff.annotation)
CDS
exon
five_prime_UTR
gene
start_codon
stop_codon
stop_codon_redefined_as_selenocysteine
three_prime_UTR
transcript
"